language: python
python:
  - "3"
install:
  - pip install -r requirements.txt
cache: pip
script:
  # crawel and update history.txt
  python src/main.py -b blog_json_config/flythief.example.json -s blog_json_config/history_links.json