language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
cache: pip
script:
  # crawel and update history.txt
  ./run.sh
before_install:
  - sudo apt-get update
  - sudo apt-get install jq